version: '3.5'
services: 
  web:
    build:
      context: ./
      dockerfile: Dockerfile 
    container_name: web_owasp5
    depends_on:
      - db
    volumes : 
      - ./www:/var/www/html/
    ports:
      - 127.0.0.1:8004:80

  db:
    container_name: db_owasp5
    image: mysql:8.0
    volumes:
      - ./owasp5.sql:/docker-entrypoint-initdb.d/owasp5.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: Yoursuperpassword
      MYSQL_DATABASE: owasp5
      MYSQL_USER: admin
      MYSQL_PASSWORD: Yoursuperpassword
    ports: 
      - 127.0.0.1:6004:3306
