version: '3.8'
services: 
  web:
    build:
      context: ./
      dockerfile: Dockerfile 
    container_name: web_owasp1
    depends_on:
      - db
    volumes : 
      - ./www:/var/www/html/
    ports:
      - 127.0.0.1:8001:80

  db:
    container_name: db_owasp1
    image: mysql:8.0
    volumes:
      - ./owasp1.sql:/docker-entrypoint-initdb.d/owasp1.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: YoursuperPassword1337
      MYSQL_DATABASE: owasp1
      MYSQL_USER: admin
      MYSQL_PASSWORD: YoursuperPassword
    ports: 
      - 127.0.0.1:6001:3306
