version: '3.8'
services: 
  web:
    build:
      context: ./
      dockerfile: Dockerfile 
    container_name: web_owasp3
    depends_on:
      - db
    volumes : 
      - ./www:/var/www/html/
    ports:
      - 127.0.0.1:8003:80

  db:
    container_name: db_owasp3
    image: mysql:8.0
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: YoursuperPassword
      MYSQL_DATABASE: owasp3
      MYSQL_USER: admin
      MYSQL_PASSWORD: Yoursuperpassword
    ports: 
      - 127.0.0.1:6003:3306
